# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - '3.6.3'
warnings_are_errors: false
sudo: false
cache: packages
after_failure:
  - ./travis-tool.sh dump_logs
env:
  global:
    - NOT_CRAN=TRUE

